version: '3.1'

services:

  db:
    build:
      context: ./dockerfiles/postgres
      dockerfile: postgres.dockerfile
    restart: always
    env_file: ./env/dev/.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080