#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
    CREATE USER "${APP_USER}" WITH PASSWORD '${APP_PASSWORD}' ;
    CREATE DATABASE admin;
    GRANT ALL PRIVILEGES ON DATABASE admin TO "${APP_USER}";
EOSQL


psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
    CREATE DATABASE loan_manager;
    GRANT ALL PRIVILEGES ON DATABASE loan_manager TO "${APP_USER}";
EOSQL